services:
  frontend:
    build:
      context: ./frontend
    container_name: tfd-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: tfd-backend
    depends_on:
      - db
      - redis
    volumes:
      - ./upload:/app/upload
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: nest
      DB_PASSWORD: nest
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3000"
    networks:
      - app-network
  db:
    image: postgres:12
    container_name: tfd-db
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:5
    container_name: tfd-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: tfd-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgresdata:

networks:
  app-network:
    driver: bridge
