name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.165.154.251.30 }}
          username: ${{ secrets.sovandy }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /projects/tfd-fullstack
            git pull
            git submodule update --recursive
            docker-compose down
            docker-compose up --build -d
